#!/bin/bash

echo 'Installing tzfe-tts ...'

# todo wget
mv tzfe-tts /usr/local/bin/tzfe-tts

cp -f tzfe-tts.service  /etc/systemd/system/tzfe-tts.service

mkdir /var/lib/tzfe-tts/
mkdir /var/log/tzfe-tts/
touch /var/log/tzfe-tts/tzfe-tts.log
touch /etc/logrotate.d/tzfe-tts

#/var/log/tzfe-tts/tzfe-tts.log {
#    size 200M
#    rotate 10
#    compress
#    delaycompress
#    notifempty
#    create 0640 root root
#    sharedscripts
#    postrotate
#        systemctl reload tzfe-tts.service > /dev/null 2>&1 || true
#    endscript
#}


echo 'done'